/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaClass */

#ifndef _Included_JavaClass
#define _Included_JavaClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaClass
 * Method:    createNative
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_JavaClass_createNative__
  (JNIEnv *, jobject);

/*
 * Class:     JavaClass
 * Method:    createNative
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_JavaClass_createNative__II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JavaClass
 * Method:    destroyNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_JavaClass_destroyNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     JavaClass
 * Method:    setX
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaClass_setX
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaClass
 * Method:    setY
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_JavaClass_setY
  (JNIEnv *, jobject, jint);

/*
 * Class:     JavaClass
 * Method:    sum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JavaClass_sum
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
