/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AwesomeLib */

#ifndef _Included_AwesomeLib
#define _Included_AwesomeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AwesomeLib
 * Method:    helloFromCPP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AwesomeLib_helloFromCPP
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
