/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AwesomeLib */

#ifndef _Included_AwesomeLib
#define _Included_AwesomeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AwesomeLib
 * Method:    helloFromCPP
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AwesomeLib_helloFromCPP
  (JNIEnv *, jobject);

/*
 * Class:     AwesomeLib
 * Method:    getRandomValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_AwesomeLib_getRandomValue
  (JNIEnv *, jobject);

/*
 * Class:     AwesomeLib
 * Method:    printList
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_AwesomeLib_printList
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     AwesomeLib
 * Method:    printMatrix
 * Signature: ([[F)V
 */
JNIEXPORT void JNICALL Java_AwesomeLib_printMatrix
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     AwesomeLib
 * Method:    modifyList
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_AwesomeLib_modifyList
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     AwesomeLib
 * Method:    createList
 * Signature: (II)[I
 */
JNIEXPORT jintArray JNICALL Java_AwesomeLib_createList
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     AwesomeLib
 * Method:    create2DList
 * Signature: (IIF)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_AwesomeLib_create2DList
  (JNIEnv *, jobject, jint, jint, jfloat);

/*
 * Class:     AwesomeLib
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AwesomeLib_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
